#!/usr/bin/env node


var fs = require('fs');
var pkg = JSON.parse(fs.readFileSync('package.json'));
process.stdout.write(
	'/* ' +
	pkg.name + ' v' + pkg.version + ' | ' +
	pkg.repository.url + ' | ' +
	'MIT License' +
	'*/\n'
);
