#!/usr/bin/env node


var path = require('path');
require('node-amd-require')(path.resolve(__dirname, '.test-amdconfig'));

var promisesAplusTests = require('promises-aplus-tests');
var adapter = require('../test/adapters/deferreds');


promisesAplusTests(adapter, {bail: true});
